name: Publish Package

permissions:
  contents: 'read'
  packages: 'write'
  id-token: 'write'

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  # if you want to cancel runs when a new one is queued, set this to true
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  # Enable debug logging for actions
  ACTIONS_RUNNER_DEBUG: true

jobs:
  checks:
    if: ${{ !contains(github.event.head_commit.message, '[skip-deploy]') }}
    timeout-minutes: 3
    runs-on: ['ubuntu-latest']
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'

      - name: Install Dependencies
        shell: bash
        run: pnpm install --frozen-lockfile

      - name: '🧹 Lint'
        shell: bash
        run: pnpm lint

      - name: '🧹 Format'
        shell: bash
        run: pnpm format

      - name: '🧪 Typecheck'
        shell: bash
        run: pnpm typecheck

      - name: '🔧 Build'
        shell: bash
        run: pnpm run build

      - name: '🧪 Test'
        shell: bash
        run: pnpm test
      
      - name: 'Check Package Structure'
        run: |
          pnpm check-package
        

  publish-npm:
    name: 'Publish Package to npm Registry'
    needs: [checks]
    permissions:
      contents: read
      packages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # https://docs.npmjs.com/generating-provenance-statements
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --access public --registry https://registry.npmjs.org --no-git-checks

  publish-gpr:
    name: 'Publish Package to GitHub Package Registry'
    needs: [checks]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          registry-url: 'https://npm.pkg.github.com'
      
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Update ~/.npmrc
        run: |
          echo "//npm.pkg.github.com:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc

      - name: 'Publish'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # https://docs.npmjs.com/generating-provenance-statements
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --access public --registry https://npm.pkg.github.com --no-git-checks

  # Generate GitHub Release Changelog
  Changelog:
    needs: [checks, publish-npm]
    permissions:
      contents: 'read'
      packages: 'write'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: 🔑 Checkout
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Generate Changelog
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx changelogen@latest
